apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-api-chart.fullname" . }}
  labels:
    app: {{ include "node-api-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "node-api-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "node-api-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"
            - name: DEPLOYMENT_ENV
              value: "{{ .Values.deploymentEnv }}"
