replicaCount: 2

image:
  repository: vramprasad/node-api-helm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

containerPort: 3000

deploymentEnv: "staging"